trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Login to Docker Hub'
    inputs:
      command: login
      containerRegistry: 'DockerHubConnection'

- task: Docker@2
    displayName: 'Build OrdersManagement Docker Image'
    inputs:
      command: build
      repository: bluesurviver/ordersmanagement
      dockerfile: 'OrdersManagement/Dockerfile'
      buildContext: $(Build.SourcesDirectory)
      tags: latest

  - task: Docker@2
    displayName: 'Build BorrowingManagement Docker Image'
    inputs:
      command: build
      repository: bluesurviver/borrowingmanagement
      dockerfile: 'BorrowingManagement/Dockerfile'
      buildContext: $(Build.SourcesDirectory)
      tags: latest

- task: Docker@2
    displayName: 'Build InventoryManagement Docker Image'
    inputs:
      command: build
      repository: bluesurviver/inventorymanagement
      dockerfile: 'InventoryManagement/Dockerfile'
      buildContext: $(Build.SourcesDirectory)
      tags: latest

  - task: Docker@2
    displayName: 'Push OrdersManagement Docker Image to Docker Hub'
    inputs:
      command: push
      repository: bluesurviver/ordersmanagement
      tags: latest

  - task: Docker@2
    displayName: 'Push BorrowingManagement Docker Image to Docker Hub'
    inputs:
      command: push
      repository: bluesurviver/borrowingmanagement
      tags: latest

  - task: Docker@2
    displayName: 'Push InventoryManagement Docker Image to Docker Hub'
    inputs:
      command: push
      repository: bluesurviver/inventorymanagement
      tags: latest

  - task: Kubernetes@1
    displayName: 'Deploy to AKS'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'KubernetesServiceConnection'
      namespace: 'default'
      command: 'apply'
      arguments: '-f azure-deployment.yaml'