trigger:
  branches:
    include:
      - main  # Change if using a different branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      repository: bluesurviver/library-borrowing-system
      dockerfile: '**/Dockerfile'
      tags: latest

  - task: Docker@2
    displayName: 'Push Docker Image to Docker Hub'
    inputs:
      command: push
      repository: bluesurviver/library-borrowing-system
      tags: latest
      containerRegistry: dockerhub

  - task: Kubernetes@1
    displayName: 'Deploy to AKS'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'AKS-Cluster'
      namespace: 'default'
      command: 'set'
      arguments: 'image deployment/library-system library-container=bluesurviver/library-borrowing-system:latest --record'
